[database]

neo4j_endpoint = "bolt://4.154.29.162:7687"

neo4j_username = "neo4j"

neo4j_password = "Ta1ch12xy112022!"



 



sql_password = "Famicom77!"

sql_server = "impaxsqlserver.database.windows.net"

sql_database_name = "Portal"

sql_username = "portal_excel_read"



 



azure_container_conn_str = "DefaultEndpointsProtocol=https;AccountName=impaxhkstorage;AccountKey=JP0AK1g5wtimYcuUZy9R3rIXi/A9qLIx/grnzzC9sliXnAwalR23EH1V//CVQaTakyXFKoyU7IOy+AStq/5hCQ==;EndpointSuffix=core.windows.net"



 



[users]

password = "temporarypassword"



 



[external_links]

neodash_url = "https://iqra840.github.io/nd_demo/"
